import {createSlice } from "@reduxjs/toolkit";

const initialState = {
   itemDocId  : null,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.


export const appSlice = createSlice({
  name: "counter",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    enterItem: (state,action) => {
      state.itemDocId  = action.payload.itemDocId;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
 
});

export const { enterItem } = appSlice.actions;

export const selectedItemId = (state) => state.app.itemDocId;

export default appSlice.reducer;



